name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create a daily commit
      run: |
        echo "Update on $(date)" >> daily_commit.txt
        git add daily_commit.txt
        git commit -m "Update on $(date)"
        git push
